### PR TITLE
Avoid running earlier successes with --quickcheck-replay

### LINKED ISSUE #383: QuickCheck: allow to print/specify seed for a failure without having to replay through previous successes
If we find a property test failure after a lot of iterations, reproducing it is annoying as we have to replay all successful iterations to get to the failing test case. This is a bit annoying:

 - major: reproducing the failure can take a long time when testing with lots of iterations and/or long test durations per test (especially true for long-running nightly tests) 
 - minor: ad-hoc debugging statements via eg `Debug.Trace` are also printed for all previous successful cases

Also see https://github.com/hedgehogqa/haskell-hedgehog/pull/454 for a recent Hedgehog PR implementing this (and more).

I think this should be simple to implement in tasty-quickcheck as QuickCheck exposes the necessary seed in its [`Result`](https://hackage.haskell.org/package/QuickCheck-2.14.3/docs/Test-QuickCheck.html#t:Result):

```haskell
data Result
  = ...
  | Failure
    { ...
    , usedSeed        :: QCGen
      -- ^ What seed was used
    , usedSize        :: Int
      -- ^ What was the test size
    ...
    }
...

data Args
  = Args
  { replay          :: Maybe (QCGen,Int)
    -- ^ Should we replay a previous test?
  , ...
  }
```

On failure, `(usedSeed, usedSize)` would be printed, and it could be specified via a new flag `--quickcheck-exact-replay` (name very tentative).

Happy to open a PR if this sounds like a useful addition.

### PR DESCRIPTION
**Pull request by facundominguez**
On failure, tasty-quickcheck now suggests string seeds (with an implementation-dependent structure). Integer seeds are still accepted as input though.

Fixes #383

### CODE REVIEW

File: quickcheck/Test/Tasty/QuickCheck.hs [hunk 1]
```diff
@@ -169,34 +179,41 @@ instance IsOption QuickCheckMaxShrinks where
 -- but may be used by others.
 --
 -- @since 0.9.1
-optionSetToArgs :: OptionSet -> IO (Int, QC.Args)
+optionSetToArgs :: OptionSet -> IO QC.Args
```
Comment (facundominguez) [inline quickcheck/Test/Tasty/QuickCheck.hs:182]: Notice the API breaking change. `optionSetToArgs` is exported.

File: quickcheck/Test/Tasty/QuickCheck.hs [hunk 2]
```diff
@@ -259,9 +277,12 @@ successful r =
...
 
-makeReplayMsg :: Int -> Int -> String
-makeReplayMsg seed size = let
-    sizeStr = if (size /= defaultMaxSize)
-                 then printf " --quickcheck-max-size=%d" size
-                 else ""
-  in printf "Use --quickcheck-replay=%d%s to reproduce." seed sizeStr
+makeReplayMsg :: (QCGen, Int) -> String
+makeReplayMsg seedSz =
+  printf "Use --quickcheck-single-replay=\"%s\" to reproduce." (show seedSz)
```
Comment (facundominguez) [inline quickcheck/Test/Tasty/QuickCheck.hs:282]: Probably we should display both the value of `--quickcheck-replay` and `--quickcheck-single-replay` here. Otherwise, the user of `--quickcheck-replay` has no way to get a seed.

File: quickcheck/Test/Tasty/QuickCheck.hs (hunk 1 above)
Comment (Bodigrim) [reply quickcheck/Test/Tasty/QuickCheck.hs:183]: I don't see a reason for breakage though. You can still return `(Int, QC.Args)`.

File: quickcheck/Test/Tasty/QuickCheck.hs (hunk 2 above)
Comment (Bodigrim) [reply quickcheck/Test/Tasty/QuickCheck.hs]: What are the remaining use cases for `--quickcheck-replay` now? I guess you can just reuse it without introducing a new command line flag.

File: quickcheck/Test/Tasty/QuickCheck.hs (hunk 1 above)
Comment (facundominguez) [reply quickcheck/Test/Tasty/QuickCheck.hs]: Indeed. I reverted this.

File: quickcheck/Test/Tasty/QuickCheck.hs (hunk 2 above)
Comment (facundominguez) [reply quickcheck/Test/Tasty/QuickCheck.hs]: I don't know who is relying on the old behavior. I'm happy to break that if nobody cares.

Comment (Bodigrim) [reply quickcheck/Test/Tasty/QuickCheck.hs]: I find it hard to imagine that someone would consciously prefer old behaviour to a new, but it seems you can support both without too much trouble. If it's `--quickcheck-replay=(QCGen ..., 42)` do a new thing, if it's `--quichckeck-replay=QCGen...` do the old thing.

Comment (facundominguez) [reply quickcheck/Test/Tasty/QuickCheck.hs]: And when printing, should we show both forms when sensible?

Comment (Bodigrim) [reply quickcheck/Test/Tasty/QuickCheck.hs]: Showing one form would be enough IMO.

Comment (facundominguez) [reply quickcheck/Test/Tasty/QuickCheck.hs]: It can be done as you suggest. But note that the old form is unusable if the user has no way to discover the seeds that go with it. What would be the purpose of keeping the old form then?

Comment (Bodigrim) [reply quickcheck/Test/Tasty/QuickCheck.hs]: Just an escape hatch. I do not see why a user might want the old behavior back; but someone could have a regression script still using an old format. Not crashing in such scenario would be useful.

Comment (facundominguez) [reply quickcheck/Test/Tasty/QuickCheck.hs]: Pushed. Also added a note to the change log. Thanks for your review @Bodigrim!

File: quickcheck/CHANGELOG.md [hunk 3]
```diff
@@ -1,6 +1,18 @@
 Changes
 =======
 
+Next Version
+------------
+
+* Produce seeds that run a single failing tests instead of reproducing
+  all the earlier successes ([#410](https://github.com/UnkindPartition/tasty/pull/410)).
+
+  Seeds are now strings, instead of single integers. e.g.
```
Comment (Bodigrim) [inline quickcheck/CHANGELOG.md:10]:
```suggestion
  Seeds are now strings, instead of single integers, e.g.
```

File: quickcheck/Test/Tasty/QuickCheck.hs [hunk 4]
```diff
@@ -82,7 +82,10 @@ testProperties name = testGroup name . map (uncurry testProperty)
 newtype QuickCheckTests = QuickCheckTests Int
   deriving (Num, Ord, Eq, Real, Enum, Integral, Typeable)
 
-newtype QuickCheckReplay = QuickCheckReplay (Maybe Int)
+-- | Replay seed. The @Left int@ form is kept for legacy purposes.
+-- The form @Right (qcgen, intSize)@ holds both the seed and the size
+-- to run QuickCheck tests.
+newtype QuickCheckReplay = QuickCheckReplay (Maybe (Either Int (QCGen, Int)))
```
Comment (Bodigrim) [inline quickcheck/Test/Tasty/QuickCheck.hs:88]: Could it be
```suggestion
newtype QuickCheckReplay = QuickCheckReplay (Maybe (Int, Maybe QCGen))
```
?

File: quickcheck/Test/Tasty/QuickCheck.hs [hunk 5]
```diff
@@ -168,30 +173,37 @@ instance IsOption QuickCheckMaxShrinks where
 -- This is a low-level function that was originally added for tasty-hspec
 -- but may be used by others.
 --
+-- The returned Int is kept only for backward compatibility purposes. It
+-- has no use in tast-quickcheck.
```
Comment (Bodigrim) [inline quickcheck/Test/Tasty/QuickCheck.hs:177]:
```suggestion
-- has no use in @tasty-quickcheck@.
```

**Review by Bodigrim — COMMENTED** [review]
A few more wibbles, but overall looks good to me, thanks!

CC @andreasabel @martijnbastiaan @VictorCMiraldo to review.

File: quickcheck/Test/Tasty/QuickCheck.hs (hunk 4 above)
Comment (facundominguez) [reply quickcheck/Test/Tasty/QuickCheck.hs:88]: I find the code easier to approach as it is.

* The two Ints in the Either type have different meanings, whether the meaning of the Int in the Maybe form depends on the value of the second component of the pair.

* The quickcheck API can take the pair `(QCGen, Int)` as is without further ado.

But let me know if you still think the `Maybe` form is to be preferred.

Another option is to use a custom type:
```haskell
data Seed = OldSeed Int | NewSeed (QCGen, Int)
```

Comment (Bodigrim) [reply quickcheck/Test/Tasty/QuickCheck.hs:88]: OK, unless someone else feels strongly about it, I'm fine to keep it as is.

**Comment by facundominguez** [comment]
Thanks @martijnbastiaan 

> I do like a custom data type better (Seed/QuickCheckReplay),

I contributed an implementation of this idea in https://github.com/facundominguez/tasty/pull/1.
I could make it a follow up PR, or maintainers can cherry-pick it if they wish.

**Comment by Bodigrim** [comment]
> I contributed an implementation of this idea in [facundominguez#1](https://github.com/facundominguez/tasty/pull/1).
> I could make it a follow up PR to `UnkindPartition/tasty` or maintainers can cherry-pick it if they wish.

This looks nice. Please add it to this PR + mention the change to `QuickCheckReplay` in the changlog + bump major version of `tasty-quickcheck` - and I think we'll be good to merge.

**Comment by Bodigrim** [comment]
+ please ensure that everything has correct `@since` pragmas.

**Comment by facundominguez** [comment]
> - [x] add it to this PR
> - [x] mention the change to `QuickCheckReplay` in the changelog
> - [x] bump major version of `tasty-quickcheck`

> - [ ] please ensure that everything has correct `@since` pragmas.

I added "@since 0.11" tags to the data constructors of the `QuickCheckReplay` data type. Let me know if more tags are needed.

**Comment by Bodigrim** [comment]
@facundominguez thanks! `README.md` can use an update too, if you are up to it.

@amesgen as an original author of #383, are you happy with this solution?

**Comment by facundominguez** [comment]
> README.md can use an update too, if you are up to it.

I'm a bit embarrassed to admit that I cannot discover on my own what needs updating there. :facepalm:

**Review by amesgen — APPROVED** [review]
This looks excellent!

**Comment by Bodigrim** [comment]
> I'm a bit embarrassed to admit that I cannot discover on my own what needs updating there. 🙈

@facundominguez the output of `--help` could be updated, but I'm not sure it was kept up-to-date before anyway. 

Thanks for your contribution, merging.
