### PR TITLE
Fix colors in console reporter, resolves #298

### LINKED ISSUE #298: Font color in some contexts might be indistinguishable from terminal foreground color
I noticed this when running tests and benchmarks of `bytestring`, which uses tasty (and tasty-bench). Compare
Screenshot_20210419_013308
vs
Screenshot_20210419_013334

So far this looks like a tasty's issue, as I don't think I ever noticed anything that might hint it's a color scheme issue.

### PR DESCRIPTION
**Pull request by Bodigrim**
No need to be clever, just `putStr` :)

### CODE REVIEW

File: core/Test/Tasty/Ingredients/ConsoleReporter.hs [hunk 1]
```diff
@@ -709,7 +709,9 @@ ok, fail, skipped, infoOk, infoFail :: (?colors :: Bool) => String -> IO ()
 fail     = output failFormat
 ok       = output okFormat
 skipped  = output skippedFormat
-infoOk   = output infoOkFormat
+-- Just default foreground color for 'infoOk'; do not apply 'infoOkFormat',
+-- because terminal's background could be white itself. See #298.
```
Comment (andreasabel) [inline core/Test/Tasty/Ingredients/ConsoleReporter.hs:713]: Yeah, that is the usual problem with coloring output.

We have the same problem when considering coloring errors for Agda.
- https://github.com/agda/agda/pull/6544

It would be great to have _symbolic_ colors, that resolve to physical color according to some (standard or custom) coloring scheme, depending on the background color.
I haven't found any Haskell solution to that problem yet (that at least works well on modern terminals).

Comment (Bodigrim) [reply core/Test/Tasty/Ingredients/ConsoleReporter.hs:713]: Yeah, I'm not aware of any fundamental solution. Other colors used by `tasty` are less problematic: it's highly unlikely that someone has a terminal with red or green background; it's only `infoOkFormat` who poses an issue.

**Review by andreasabel — APPROVED** [review]
Of course I approve.
